query reviewsByProductId($productId: String!, $orderBy: String) {
  reviewsByProductId(
    productId: $productId
    from: 0
    to: 1000
    orderBy: $orderBy
  ) {
    data {
      title
      text
      reviewerName
      reviewDateTime
      approved
      id
      rating
    }
  }

  averageRatingByProductId(productId: $productId) {
    average
    starsFive
    starsFour
    starsThree
    starsTwo
    starsOne
    total
  }
}
